---
info:
    app:
        name: 'Vacation bot'
        description: 'The web application'
        version: 1.0.0

spring:
    data:
        mongodb:
          host: localhost
          port: 27017
          database: devbot

management:
  context-path: /
